mod graph;
mod land;
mod router;
mod los;
mod server;
mod generate;
mod graph_builder;
mod canals;
mod audit;
mod waterways;
mod channels;

use std::sync::Arc;
use std::time::Instant;



#[tokio::main]
async fn main() {
    let args: Vec<String> = std::env::args().collect();

    let command = args.get(1).map(|s| s.as_str()).unwrap_or("serve");

    match command {
        "generate" => run_generate(&args).await,
        "serve" => run_server(&args).await,
        "audit" => run_audit(&args),
        "find-channels" => run_find_channels(&args),
        _ => {
            println!("🌊 Sea Router (Rust)");
            println!();
            println!("Usage:");
            println!("  sea-router-rs generate [depth] [data-dir]  Build the sea routing graph");
            println!("  sea-router-rs serve [data-dir]             Start the HTTP server");
            println!("  sea-router-rs audit [ports.json] [data-dir] Report how far each port snaps to the graph");
            println!("      --write-baseline                       Freeze the result as the regression baseline");
            println!("  sea-router-rs find-channels [data-dir]      Search exact geometry for channels to unreachable ports");
            println!();
            println!("Defaults: depth=16, data-dir=../data");
        }
    }
}

/// Search for a navigable channel to every port the router cannot reach, and
/// write the results as corridors. Ports that already attach cleanly are left
/// alone; the point is to find the fjord and strait channels the raster hides.
fn run_find_channels(args: &[String]) {
    let positional: Vec<&str> = args[2..]
        .iter()
        .map(|s| s.as_str())
        .filter(|s| !s.starts_with("--"))
        .collect();
    let data_dir = positional.first().copied().unwrap_or("../data");

    let ports = audit::load_ports(&find_ports_fixture().expect("ports fixture"))
        .expect("ports fixture");
    let graph = graph::Graph::load(&format!("{}/graph/sea-graph.json", data_dir))
        .expect("graph");
    let classifier = land::LandClassifier::load(&land_path(data_dir)).expect("land data");

    let full_index = graph.build_full_index();
    let reports = audit::snap_ports(&graph, &classifier, &ports, &full_index);
    let stuck: Vec<&audit::Port> = reports
        .iter()
        .filter(|r| !r.connector_clear)
        .filter_map(|r| ports.iter().find(|p| p.name == r.name && p.lon == r.lon))
        .collect();

    println!("\n🌊 Searching channels for {} unreachable ports\n", stuck.len());

    let t0 = Instant::now();
    let mut feats: Vec<serde_json::Value> = Vec::new();
    let mut failed: Vec<&str> = Vec::new();
    for p in &stuck {
        match channels::find_channel(&graph, &classifier, p) {
            Some(ch) => {
                let km: f64 = ch.points.windows(2)
                    .map(|w| {
                        let (a, b) = (w[0], w[1]);
                        let dlat = (b[1] - a[1]) * 111.0;
                        let dlon = (b[0] - a[0]) * 111.0 * a[1].to_radians().cos().abs();
                        (dlat * dlat + dlon * dlon).sqrt()
                    })
                    .sum();
                println!("  found  {:<32} {:>4} pts {:>7.1} km", ch.port, ch.points.len(), km);
                feats.push(serde_json::json!({
                    "type": "Feature",
                    "properties": {
                        "port": ch.port,
                        "name": format!("{} channel", ch.port),
                        "kind": "channel",
                        "halfWidthKm": 0.8,
                    },
                    "geometry": { "type": "LineString", "coordinates": ch.points },
                }));
            }
            None => {
                println!("  none   {}", p.name);
                failed.push(&p.name);
            }
        }
    }

    let out = "../data/waterways-channels.geojson";
    std::fs::write(
        out,
        serde_json::to_string_pretty(&serde_json::json!({
            "type": "FeatureCollection",
            "_comment": "GENERATED by `sea-router-rs find-channels`. Paths found by \
                         searching exact ring geometry outward from each unreachable \
                         port until it meets raster-visible water.",
            "features": feats,
        }))
        .unwrap(),
    )
    .expect("write channels");

    println!(
        "\n  {} channels found, {} without one, in {:.0}s -> {}",
        feats.len(), failed.len(), t0.elapsed().as_secs_f64(), out
    );
    if !failed.is_empty() {
        println!("  no channel: {}", failed.join(", "));
    }
}

/// The port fixture drives port-node injection, so a silent miss would produce
/// a graph that looks fine and routes badly. Checked from both the repo root
/// (how CI invokes generate) and from rust/ (how a developer does).
fn find_ports_fixture() -> Option<String> {
    ["rust/tests/fixtures/ports.json", "tests/fixtures/ports.json"]
        .into_iter()
        .find(|p| std::path::Path::new(p).exists())
        .map(|s| s.to_string())
}

/// Resolve the land polygon file, preferring OSM over the Natural Earth fallback.
fn land_path(data_dir: &str) -> String {
    let osm = format!("{}/osm_land_simplified.geojson.json", data_dir);
    if std::path::Path::new(&osm).exists() {
        osm
    } else {
        format!("{}/ne_10m_land.geojson.json", data_dir)
    }
}

fn run_audit(args: &[String]) {
    let write_baseline = args.iter().any(|a| a == "--write-baseline");
    let positional: Vec<&str> = args[2..]
        .iter()
        .map(|s| s.as_str())
        .filter(|s| !s.starts_with("--"))
        .collect();
    let ports_path = positional.first().copied().unwrap_or("tests/fixtures/ports.json");
    let data_dir = positional.get(1).copied().unwrap_or("../data");

    let ports = audit::load_ports(ports_path).expect("Failed to load ports fixture");
    println!("🌊 Sea Router — Port Snap Audit ({} ports)\n", ports.len());

    let graph = graph::Graph::load(&format!("{}/graph/sea-graph.json", data_dir))
        .expect("Failed to load graph");
    let classifier = land::LandClassifier::load(&land_path(data_dir))
        .expect("Failed to load land data");

    let t0 = Instant::now();
    let full_index = graph.build_full_index();
    let mut reports = audit::snap_ports(&graph, &classifier, &ports, &full_index);
    println!("\n  Snapped {} ports in {}ms\n", reports.len(), t0.elapsed().as_millis());

    let mut dists: Vec<f64> = reports.iter().map(|r| r.snap_km).collect();
    dists.sort_by(|a, b| a.partial_cmp(b).unwrap());
    println!(
        "  p50={:.2}km  p90={:.2}km  p99={:.2}km  max={:.2}km",
        audit::percentile(&dists, 0.50),
        audit::percentile(&dists, 0.90),
        audit::percentile(&dists, 0.99),
        dists.last().copied().unwrap_or(0.0),
    );
    let fallbacks = reports.iter().filter(|r| !r.connector_clear).count();
    println!("  {} ports fell back to the nearest node (no clear connector)\n", fallbacks);

    reports.sort_by(|a, b| b.snap_km.partial_cmp(&a.snap_km).unwrap());
    println!("  Worst 40:");
    println!(
        "  {:>9}  {:>5}  {:<32} {:>5}  {:>9}  {:>9}",
        "snap km", "days", "port", "conn", "near any", "comp size"
    );
    for r in reports.iter().take(40) {
        println!(
            "  {:>9.2}  {:>5}  {:<32} {:>5}  {:>9.2}  {:>9}",
            r.snap_km,
            r.days,
            format!("{} ({})", r.name, r.country),
            if r.connector_clear { "ok" } else { "FALL" },
            r.nearest_any_km,
            if r.nearest_any_is_main { "main".to_string() } else { r.nearest_any_comp_size.to_string() },
        );
    }

    let out = format!("{}/port-snap-audit.json", data_dir);
    std::fs::write(&out, serde_json::to_string_pretty(&reports).unwrap()).ok();
    println!("\n  Full report: {}", out);

    if write_baseline {
        let path = "tests/fixtures/snap-baseline.json";
        let lines: Vec<String> = audit::to_baseline(&reports)
            .iter()
            .map(|b| format!("  {}", serde_json::to_string(b).unwrap()))
            .collect();
        std::fs::write(path, format!("[\n{}\n]\n", lines.join(",\n")))
            .expect("Failed to write baseline");
        println!("  Baseline written: {}", path);
    }
}

async fn run_generate(args: &[String]) {
    let max_depth: u8 = args.get(2).and_then(|s| s.parse().ok()).unwrap_or(16);
    let data_dir = args.get(3).map(|s| s.as_str()).unwrap_or("../data");

    let t0 = Instant::now();
    println!("\n🌊 Sea Router — Graph Generation (max depth: {})\n", max_depth);

    // Load land data
    println!("Step 1: Loading land data...");
    let land_path = format!("{}/osm_land_simplified.geojson.json", data_dir);
    let land_path = if std::path::Path::new(&land_path).exists() {
        land_path
    } else {
        format!("{}/ne_10m_land.geojson.json", data_dir)
    };
    let classifier = land::LandClassifier::load(&land_path).expect("Failed to load land data");
    println!("  {} land rings loaded\n", classifier.ring_count());

    // Build quadtree
    println!("Step 2: Building quadtree...");
    let mut root = generate::build_quadtree(&classifier, max_depth);
    let (water, land) = generate::count_leaves(&root);
    println!("  Water leaves: {}", water);
    println!("  Land leaves: {}\n", land);

    // Coarsen
    println!("Step 3: Coarsening open water...");
    generate::coarsen(&mut root);
    let (water_after, _) = generate::count_leaves(&root);
    println!("  Water leaves after: {}\n", water_after);

    // Build graph
    println!("Step 4: Building adjacency graph...");
    let leaves = generate::collect_water_leaves(&root);
    // Ports become graph nodes so routes start exactly where the ship docks.
    let ports_path = find_ports_fixture();
    let ports = match ports_path.as_deref().map(audit::load_ports) {
        Some(Ok(p)) => p,
        Some(Err(e)) => panic!("Port fixture failed to parse: {}", e),
        None => panic!(
            "Port fixture not found. Run `generate` from the repo root or from \
             rust/, or the graph would be built without port nodes and every \
             port would snap to open water."
        ),
    };
    println!("  {} ports to inject from {}", ports.len(), ports_path.unwrap());
    let graph_output = graph_builder::build_graph(&leaves, &classifier, &ports);

    // Save
    println!("\nStep 5: Saving graph...");
    let output_path = format!("{}/graph/sea-graph.json", data_dir);

    // Ensure directory exists
    if let Some(parent) = std::path::Path::new(&output_path).parent() {
        std::fs::create_dir_all(parent).ok();
    }

    let data = serde_json::json!({
        "nodeCount": graph_output.node_count,
        "edgeCount": graph_output.edge_count,
        "nodes": graph_output.nodes,
        "edges": graph_output.edges,
    });

    std::fs::write(&output_path, serde_json::to_string(&data).unwrap())
        .expect("Failed to write graph");

    let size_mb = std::fs::metadata(&output_path)
        .map(|m| m.len() as f64 / 1_048_576.0)
        .unwrap_or(0.0);

    println!("  Saved to {} ({:.1}MB)", output_path, size_mb);

    let elapsed = t0.elapsed().as_secs_f64();
    println!(
        "\n✅ Done in {:.1}s — {} nodes, {} edges",
        elapsed, graph_output.node_count, graph_output.edge_count
    );
}

async fn run_server(args: &[String]) {
    let t0 = Instant::now();
    println!("🌊 Sea Router (Rust) — Loading...");

    let data_dir = args.get(2).map(|s| s.as_str()).unwrap_or("../data");

    // Load graph
    let graph_path = format!("{}/graph/sea-graph.json", data_dir);
    let graph = graph::Graph::load(&graph_path).expect("Failed to load graph");
    println!(
        "  {} nodes, {} edges loaded in {}ms",
        graph.node_count, graph.edge_count,
        t0.elapsed().as_millis()
    );

    // Load land classifier
    let land_path = format!("{}/osm_land_simplified.geojson.json", data_dir);
    let land_path = if std::path::Path::new(&land_path).exists() {
        land_path
    } else {
        format!("{}/ne_10m_land.geojson.json", data_dir)
    };
    let classifier = land::LandClassifier::load(&land_path).expect("Failed to load land data");
    println!(
        "  {} land rings loaded in {}ms",
        classifier.ring_count(),
        t0.elapsed().as_millis()
    );

    let viewer_path = format!("{}/../viewer.html", data_dir);
    let node_count = graph.node_count;
    let state = Arc::new(server::AppState {
        graph,
        classifier,
        viewer_path,
        router: std::sync::Mutex::new(router::Router::new(node_count)),
    });

    println!(
        "\n🚀 API running at http://localhost:3001 (loaded in {}ms)",
        t0.elapsed().as_millis()
    );

    server::run(state).await;
}
